### PR TITLE
Added Monad, MonadPlus, and MonadFix instance to Concurrently

### LINKED ISSUE #69: Idea for Monad instance of Concurrently compatible with the Applicative Instance
The obvious way to make Concurrently into a Monad doesn't work, since then Monad would be sequential, but Applicative would be concurrent (whereas Monad is usually supposed to be a generalization of Applicative). There is a way to make a Monad instance though that is as concurrent as possible (in particular, `ap` would be perfectly concurrent).

The trick is the same one used for [`fixIO`](https://hackage.haskell.org/package/base-4.10.0.0/docs/src/System.IO.html#fixIO). Given `x :: Concurrently a` and `f :: a -> Concurrently b`, we use [`unsafeInterleaveIO`](https://hackage.haskell.org/package/base-4.10.0.0/docs/System-IO-Unsafe.html) to start a thread to put `x` into a MVar (or TMVar or Async), and then use `unsafeInterleaveIO` to read the value from the variable lazily. We can then start `f`'s action. If `f` needs `x`'s value to do anything, it will be sequential. On the other hand, if `f` does not use `x`'s value at all (such as in `ap`), it will be perfectly concurrent. It can also be anywhere in between.

I can do the code if you think this is a good concept. I just thought I'd check with you first to make sure its a good idea though.

### LINKED ISSUE #70: Idea: Give Async a Monad and MonadPlus instance
We would need to add a `Pure :: a -> Async a` data constructor to `Async`, but other than that, the current `Async` type supports the `Monad` and `MonadPlus` typeclasses. This is because `STM` is a `Monad` and `MonadPlus`.

`return` would equal `Pure`, obviously. `Pure a >>= f = f a`. For `x >>= f` where `x` isn't `Pure`, we give the resulting async `x`'s `asyncThreadId`, and use the `STM` monad to generate the resulting `_asyncWait`.

The `MonadPlus` instance would be similar, with `mzero` corresponding to `STM`'s `mzero` (and some junk `ThreadId`) and `mplus` corresponding to `STM`'s `mplus` (and choosing the left `ThreadId` (or `mzero`'s `ThreadId`).

If you don't want to add a new data constructor to `Async`, you can also define an `Applicative` and Alternative instance without changing the type at all. `pure a` would have a junk `asyncThreadId` and would use `STM`'s pure for `asyncThreadId`. `<*>` would use `STM`'s `<*>` for `_asyncWait`, and would choose the left-most non-junk-`asyncThreadId` for the resulting `asyncThreadId`. `Alternative` would work similarly. (If you do not like using an invalid `ThreadId` for `asyncThreadId`, you could slightly change `asyncThreadId`'s type and use `Nothing` instead. Or you could make it a `[ThreadId]` of all the threads involved.)

### PR DESCRIPTION
**Pull request by ChristopherKing42**
The Monad instance is in fact compatible with the Applicative instance. In as >>= asb, it will run concurrently if asb is lazy (such as used by `ap`) and sequential when strict.

Closes #69.

This is just tentative. I decided to implement it, since it did not take much coding. Feel free to deny this pull request.

### CODE REVIEW

**Comment by ChristopherKing42** [comment]
This can also technically be done with `mfix` instead of `unsafeInterleaveIO`, if you're more comfortable with that, but its a little trickier.

**Comment by ChristopherKing42** [comment]
Oh whoops. This closes #69, not #70.

**Comment by simonmar** [comment]
It's quite worrying that this connects concurrency to laziness. I have strong reservations about how easy this is to program with, and how maintainable the code is that uses it. Any time the programmer has to understand evaluation order I think we're in deep trouble. The places I know where this has caused problems: circular programming and parallel Strategies.

It's also concerning that this would be disturbingly easy to use. A lot of the time you could just use the Monad and get magic concurrency, but sometimes it would go wrong, and when it goes wrong it'll be really hard to debug.

(on the other hand you could level some of these concerns at Haxl, but at least there we're up front that there's magic happening. The `async` package so far is very explicit about where the concurrency happens, so allowing some magic in changes the game in a significant way.)

If there's a lot of support for this then I'm not 100% against it, but for now I'm leaning towards reject. I wouldn't be against to exposing enough internals of async so that you could build this in a separate package, though.

**Comment by ChristopherKing42** [comment]
Yeah, this was mostly just to show it was possible. Sufficient internals are exposed actually. All that if needed is `Concurrently`, `runConcurrently`, and `concurrently`, which is already exposed.

**Comment by ChristopherKing42** [comment]
Actually, it wasn't a valid monad anyways. Oh well.

**Pull request closed without merging**
