### PR TITLE
Make `cancel` uninterruptible...

### PR DESCRIPTION
**Pull request by bitonic**
...create `interruptibleCancel`, update docs.

CC @snoyberg @kantp

### CODE REVIEW

**Comment by bitonic** [comment]
Note that this fixes #43

**Comment by simonmar** [comment]
@snoyberg you said here https://github.com/simonmar/async/issues/41#issuecomment-231675464 that you wouldn't mind the `waitCatch` in `cancel` being interruptible, but what we ended up with (I only just realised) is that it is uninterruptible in the context of `withAsync`, and this ticket argues for it always to be uninterruptible.

Do we really want either of those?

**Comment by bitonic** [comment]
@simonmar me and @snoyberg had various discussions after that comment and he agreed that uninterruptible `cancel` by default is the way to go. I think he'll also be available later today so he can reply himself :)

**Comment by simonmar** [comment]
could you make fde3c6d052bfe190a1282792555ec1c57dc2525f a separate pull request please?

**Comment by snoyberg** [comment]
I was mistaken in that comment, as @bitonic convinced me. We _definitely_ need to deliver the exception to the child thread, so making the `cancel` uninterruptible makes sense. There's still an argument for making the `waitCatch` interruptible.

**Comment by simonmar** [comment]
@snoyberg it was the `waitCatch` I was talking about (and what your earlier comment was about).  Since `uninterruptibleCancel` now includes the `waitCatch`, the `waitCatch` in `withAsync` is now uninterruptible.  Is that what we want?

**Pull request closed without merging**
