### PR TITLE
Sync & failed

### PR DESCRIPTION
**Pull request by phadej**
I have to admit that having `sync` might result in incorrect usage, but I had use-cases where I did:
```hs
a <- async (pure value)
```

And that felt somehow un-elegant.

I stored `Async` values in a container to be waited / cancelled later. Optionally I could have saved `(wait a, cancel a)` action pairs, but that felt a bit un-elegant as well.

If this is totally wrong, I'm happy to write a section into documentation why those functions do not exist.

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
> If this is totally wrong

This is totally wrong =P

**Comment by phadej** [comment]
... and mind you explain, why?

**Comment by mitchellwrosen** [comment]
Because `sync = unsafePerformIO (forkIO (pure ())` is just a totally insane way to make a `ThreadId` out of thin air just to get this combinator.

If you are storing some `Async a` to wait on later, but some are already computed, could you instead store `Either a (Async a)`?

**Comment by phadej** [comment]
I'd be happy to use some less insance way to make `ThreadId`.
In my use case, it is simpler to use `async (pure x)` as I'm in IO, forking a haskell thread isn't that expensive, or is it?

**Comment by mitchellwrosen** [comment]
Forking a Haskell thread is not expensive per se, but this still seems like a misuse of the library. What you want can be accomplished using `pure` and `throwIO`.

Can you show a use case for these functions?

(Also FYI a Haskell thread cannot be garbage collected until its `ThreadId` reference is dropped)

**Comment by phadej** [comment]
(that thread would been shared across all `sync` created `Async` objects, so even it's a leak, it's a constant one)

I don't insist about having those combinators there. But then I'd like to have documentation discussing their absence. There are analogues in probably any Future/Promise -library, so I'm probably not the only one looking for them.

Actually I went forward and have a `LVar` which can be initialised with either `Async` or concrete value, but can be written only using the concrete value. I use it for startup procedure of the service.

**Comment by mitchellwrosen** [comment]
> There are analogues in probably any Future/Promise -library, so I'm probably not the only one looking for them.

But other future/promise libraries probably are not in pure functional languages, so they do not track side effects in the type system a la `IO` :)

The combinators are here, just hidden:

```haskell
sync :: a -> IO (Async a)
sync = async . pure

failed :: Exception e => e -> IO (Async a)
failed = async . throwIO
```

**Comment by phadej** [comment]
Well, no. In *Scala* [`Future.successful`](https://github.com/scala/scala/blob/8f567bc9c01e29624f5b7fcce40a0ee7fe261c08/src/library/scala/concurrent/Future.scala#L626`) doesn't do IO, in comparison to [`Future.apply`](https://github.com/scala/scala/blob/8f567bc9c01e29624f5b7fcce40a0ee7fe261c08/src/library/scala/concurrent/Future.scala#L652) which does (and yes, it's visible from type signature ;) )

**Comment by mitchellwrosen** [comment]
Well the difference there is that `Future.apply` takes an explicit "execution context", whereas `async` is hard-coded to use the concurrent Haskell runtime. So, you indeed _can_ create a Future "purely" as 

```
Action -> ExecutionContext -> Future
```

but in `async`, it comes out looking like

```
Action -> IO Future
```

My point is that creating `Async`s themselves just _are_ in IO, so there is not a good `a -> Async a` function that you are after.

**Comment by simonmar** [comment]
@phadej, thanks for the contribution and the discussion, however I don't think we want to do this.`Async` is an `IO` library, so I don't think it makes a lot of sense to go to extreme lengths to get `a -> Async a` instead of `a -> IO (Async a)`, and the latter is easy via `async . pure`.

**Pull request closed without merging**
